name: Build docker image

on:
  push:
    branches:
      - main

    tags:
      - '*'

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  mysqldb-8030:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v2
    - uses: ./.github/actions
      with:
        version: '8.0.30'
        tags: '8.0,8,latest'
        workdir: 8
#        platform: linux/amd64,linux/arm64
        platform: linux/amd64